version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: scrapy_backend
    depends_on:
      - database_scrapy
    env_file:
      - .env
    ports:
      - "8090:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: scrapy_frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "88:4321"
    restart: unless-stopped

  database_scrapy:
    image: postgres:15
    container_name: scrapy_db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
